    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"
        continue-on-error: true # <-- Bunu ekliyoruz. Dal yoksa hata vermeden devam etmesini sağlar.
