name: Build and Publish

on:
  push:
    branches:
      - master # Eğer ana dalınız main ise burayı main yapın

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"
        continue-on-error: true
